version: '3.9'

services:
  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    environment: &mysql_env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dealdeli_data
    ports:
      - "3306:3306"
    volumes:
      - ./databases/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dealdeli-net


  user_microservice:
    build: ./user_microservice
    ports:
      - "5001:5001"
    environment:
      <<: *mysql_env
      MYSQL_HOST: mysql_container
      MYSQL_USER: root
    depends_on:
      - mysql_container
    networks:
      - dealdeli-net

  price_microservice:
    build: ./price_microservice
    ports:
      - "5002:5002"
    environment:
      <<: *mysql_env
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql_container
    networks:
      - dealdeli-net


  analytics_microservice:
    build: ./analytics_microservice
    ports:
      - "5003:5003"
    environment:
      <<: *mysql_env
      MYSQL_HOST: mysql_container
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql_container
    networks:
      - dealdeli-net

  frontend_microservice:
    build: ./frontend_microservice
    ports:
      - "5501:8000"
    networks:
      - dealdeli-net

networks:
  dealdeli-net:
